# Generated by Django 3.1.2 on 2020-10-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default_gallery.jpg', upload_to='gallery_section_pics')),
            ],
        ),
    ]
