# Generated by Django 3.1.2 on 2020-10-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_galleryfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryfolder',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='GalleryFolderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default_gallery.jpg', upload_to='gallery_section_pics/<django.db.models.fields.CharField>')),
                ('folder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.galleryfolder')),
            ],
        ),
    ]
